"""آلي الناشر — publish Aali's model to the world (OWNER'S DEPLOY BUTTON).

The owner decides what gets published and where; nothing is ever uploaded
without an explicit flag. Steps are independent and idempotent:

  python scripts/publish_aali.py --check
      Preflight: model/adapter present? HF token set? git clean? data license?

  python scripts/publish_aali.py --merge
      Merge the promoted LoRA adapter into the base model -> a standalone
      model folder ready for upload / GGUF conversion.

  python scripts/publish_aali.py --hf <owner/aali-1b> [--license apache-2.0]
      Upload the merged model (+ auto-generated model card crediting the
      owner, Hmam Kaadna) to Hugging Face. Needs HF_TOKEN in the environment
      (huggingface-cli login) — the token never passes through chat.

  python scripts/publish_aali.py --ollama aali
      Write an Ollama Modelfile + exact commands next to the merged model
      (GGUF conversion itself is a documented manual step; see
      docs/publish_aali.md).

  python scripts/publish_aali.py --openrouter
      Generate the OpenRouter listing checklist + a live probe of Aali's
      OpenAI-compatible endpoint (what OpenRouter's crawler will test).

Attribution: the model card always credits "Hmam Kaadna" as the owner and
creator (the owner's standing instruction, 2026-09-08).
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "file-agent"))

OWNER = "Hmam Kaadna"
PROMOTED = Path("D:/hwk-data/soup/promoted.json")
BASE = Path("D:/hwk-models/Qwen2.5-1.5B-Instruct")
TUNED_DIR = Path("D:/hwk-data/soup/tuned")
MERGED = Path("D:/hwk-models/aali-merged")
REPORTS = Path("D:/hwk-data/soup")
SOUP_PY = Path("D:/hwk-tools/soup-venv/Scripts/python.exe")

MODEL_CARD = """---
license: {license}
language:
  - ar
  - en
tags:
  - aali
  - arabic
  - tool-calling
  - from-scratch-project
  - qlora
library_name: transformers
base_model: {base_model}
---

# آلي (Aali) — {size}

A fine-tuned Arabic-first conversational + tool-calling model produced by the
**HWK Aali** project: a home-built AI assistant that runs on the owner's own
hardware and is served by his own server, clients and memory system.

## Owner & creator

**{owner}** — the project's sole author, data curator, and trainer.
Contact via the project repository: https://github.com/WoodbutcherTh1/HWK-Aali

## What this model is

- **Arabic-first, bilingual** (Arabic + English) chat model.
- Fine-tuned on a **curated, owner-built SFT mix**: tool-calling episodes
  (files, commands, memory, web, media), Arabic conversation data from
  public-domain sources, and security-hardening episodes (prompt-injection
  refusals, secret-redaction behaviour, contradiction surfacing).
- Trained with **QLoRA (4-bit, r=32)** on a single RTX 3070 by Soup.

## What this model is NOT

- Not affiliated with any company; not a hosted-product model.
- A 1.5B-parameter model: it will make mistakes, and it will not match
  frontier models. It exists because its owner built every part of it.

## Training data policy

Public-domain / openly licensed corpora + data captured from the owner's own
conversations with the assistant. No proprietary or leaked text is included
(project rule: learn *patterns*, not stolen text). Secrets are redacted from
all training episodes by the project's memory pipeline.

## Intended use

Chat + tool-calling inside the Aali ecosystem (server + web/desktop/CLI
clients), research, and as a from-scratch-project reference. Out of scope:
high-stakes advice, safety-critical decisions.

_Card generated by scripts/publish_aali.py on {date}._
"""


def _stamp() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def promoted_adapter() -> Path | None:
    try:
        data = json.loads(PROMOTED.read_text(encoding="utf-8"))
        adapter = Path(data.get("adapter_dir", ""))
        if adapter.is_dir() and (adapter / "adapter_model.safetensors").exists():
            return adapter
    except (OSError, ValueError):
        pass
    # fall back to the newest checkpoint-* in the tuned output
    for candidate in sorted(TUNED_DIR.glob("checkpoint-*"), reverse=True):
        if (candidate / "adapter_model.safetensors").exists():
            return candidate
    return None


def check() -> bool:
    print(f"=== publish preflight — {_stamp()} ===")
    ok = True
    adapter = promoted_adapter()
    print(f"[{'OK' if BASE.is_dir() else '!!'}] base model: {BASE}")
    ok &= BASE.is_dir()
    print(f"[{'OK' if adapter else '!!'}] trained adapter: {adapter or 'none — run the soup pipeline first'}")
    ok &= adapter is not None
    report = REPORTS / "resft_pipeline_report.md"
    print(f"[{'OK' if report.exists() else '--'}] pipeline verdict: {report if report.exists() else 'not yet (promotion gate)'}")
    token = os.getenv("HF_TOKEN", "")
    if not token:
        try:
            from huggingface_hub import HfFolder  # type: ignore
            token = HfFolder.get_token() or ""
        except Exception:  # noqa: BLE001
            pass
    print(f"[{'OK' if token else '--'}] HF token: {'present' if token else 'not set (run: huggingface-cli login)'}")
    try:
        out = subprocess.run(["git", "status", "--porcelain"], cwd=ROOT,
                             capture_output=True, text=True, timeout=30).stdout
        dirty = len(out.strip().splitlines())
        print(f"[{'OK' if dirty == 0 else '--'}] git working tree: {dirty} uncommitted files (publish only touches D:, not the repo)")
    except OSError:
        print("[--] git not found")
    merged = MERGED / "config.json"
    print(f"[{'OK' if merged.exists() else '--'}] merged model: {MERGED}" + (" (ready for upload)" if merged.exists() else " (run --merge)"))
    return ok


def merge() -> bool:
    """Merge the promoted LoRA adapter into the base model (runs in the Soup
    venv, which owns peft/transformers)."""
    adapter = promoted_adapter()
    if adapter is None:
        print("no trained adapter found — run the soup pipeline first")
        return False
    script = f"""
import torch
from peft import PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer
base = AutoModelForCausalLM.from_pretrained(r"{BASE}", torch_dtype=torch.bfloat16, device_map="cpu")
model = PeftModel.from_pretrained(base, r"{adapter}")
model = model.merge_and_unload()
model.save_pretrained(r"{MERGED}")
AutoTokenizer.from_pretrained(r"{BASE}").save_pretrained(r"{MERGED}")
print("merged ->", r"{MERGED}")
"""
    MERGED.mkdir(parents=True, exist_ok=True)
    print(f"merging {adapter.name} into {BASE.name} (CPU, ~3-5 min)…")
    completed = subprocess.run([str(SOUP_PY), "-c", script], text=True,
                               capture_output=True, encoding="utf-8", timeout=1800)
    print((completed.stdout or "")[-800:])
    if completed.returncode != 0:
        print((completed.stderr or "")[-1200:])
        return False
    card = MODEL_CARD.format(license="apache-2.0", base_model="Qwen/Qwen2.5-1.5B-Instruct",
                             size="1.5B (QLoRA-merged)", owner=OWNER, date=_stamp())
    (MERGED / "README.md").write_text(card, encoding="utf-8")
    print(f"model card written: {MERGED / 'README.md'} (credit: {OWNER})")
    return True


def hf_upload(repo_id: str, license_id: str) -> bool:
    merged_cfg = MERGED / "config.json"
    if not merged_cfg.exists():
        print("merged model missing — run --merge first")
        return False
    card = MODEL_CARD.format(license=license_id, base_model="Qwen/Qwen2.5-1.5B-Instruct",
                             size="1.5B (QLoRA-merged)", owner=OWNER, date=_stamp())
    (MERGED / "README.md").write_text(card, encoding="utf-8")
    try:
        from huggingface_hub import HfApi  # type: ignore
    except ImportError:
        print("huggingface_hub missing in this venv — run inside .venv or soup-venv")
        return False
    api = HfApi()
    api.create_repo(repo_id, exist_ok=True, private=True)  # upload private first!
    print(f"uploading {MERGED} -> {repo_id} (private; flip public when you're ready)…")
    api.upload_folder(folder_path=str(MERGED), repo_id=repo_id)
    print(f"done: https://huggingface.co/{repo_id}")
    print("review the card, then Settings → Visibility → Public when YOU decide.")
    return True


def ollama_prepare(name: str) -> bool:
    if not (MERGED / "config.json").exists():
        print("merged model missing — run --merge first (GGUF conversion is manual; see docs/publish_aali.md)")
        return False
    modelfile = MERGED / "Modelfile"
    modelfile.write_text(
        f"""# آلي — Ollama model (owner: {OWNER})
# 1) convert to GGUF once (see docs/publish_aali.md), then:
# 2) ollama create {name} -f Modelfile
FROM ./aali-q4_k_m.gguf
PARAMETER temperature 0.7
PARAMETER num_ctx 4096
SYSTEM \"\"\"You are Aali (آلي), a helpful Arabic-first assistant made by {OWNER}.
Reply in the same language as the user (Arabic first). Be precise and honest
about what you can and cannot do.\"\"\"
""",
        encoding="utf-8",
    )
    print(f"Modelfile written: {modelfile}")
    print("next: convert GGUF (llama.cpp convert_hf_to_gguf.py), then `ollama create " + name + " -f Modelfile`")
    return True


def openrouter_checklist() -> bool:
    out = REPORTS / "openrouter_checklist.md"
    out.write_text(
        f"""# نشر آلي على OpenRouter — checklist (owner: {OWNER})

_generated {_stamp()} — https://openrouter.ai/docs → "Publish your model"_

1. **Weights must be publicly hosted** (Hugging Face) — run `--hf` first and
   flip the repo public.
2. Open the OpenRouter "Publish" form and submit: repo URL, license
   (apache-2.0), context length (4096), pricing (suggested: free tier first).
3. OpenRouter probes an OpenAI-compatible endpoint you provide. Aali's own
   server already speaks this dialect: `http://<your-domain>:5055/v1`
   (keep it behind your Cloudflare tunnel; see docs/custom_domain.md).
4. Model card: use the README.md generated next to the merged model.
5. Owner payout/account details are entered by **you** in their dashboard —
   this tool deliberately never touches credentials.

### Live self-probe (run after publishing)
```
curl http://127.0.0.1:5055/v1/chat/completions -H "Content-Type: application/json" \\
  -d '{"json_payload"}'
```
""",
        encoding="utf-8",
    ).replace("{json_payload}", json.dumps({
        "model": "owner/aali-1.5b", "max_tokens": 200, "temperature": 0.0,
        "messages": [{"role": "user", "content": "مرحبا آلي، عرّف نفسك بجملة واحدة."}],
    }, ensure_ascii=False))
    print(f"checklist written: {out}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description="Publish Aali (owner's deploy button)")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--merge", action="store_true")
    parser.add_argument("--hf", metavar="REPO_ID", help="e.g. HmamK/aali-1.5b")
    parser.add_argument("--license", default="apache-2.0")
    parser.add_argument("--ollama", metavar="NAME", help="e.g. aali")
    parser.add_argument("--openrouter", action="store_true")
    args = parser.parse_args()
    sys.stdout.reconfigure(encoding="utf-8")

    if args.check or not any([args.merge, args.hf, args.ollama, args.openrouter]):
        return 0 if check() else 1
    if args.merge:
        return 0 if merge() else 1
    if args.hf:
        return 0 if hf_upload(args.hf, args.license) else 1
    if args.ollama:
        return 0 if ollama_prepare(args.ollama) else 1
    if args.openrouter:
        return 0 if openrouter_checklist() else 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
